### ISSUE TITLE
MSLiveLink-Blender-OctaneRender Prime Free Tier Offer

### ISSUE THREAD

**Issue by lemain** [Yichen-Dou/MSLiveLink-OC-Blender#2]
Hi, I really love the concept of the addon but I did not manage to get it to work.
I installed the addon but the option "Start Megascans Livelink Octane" is greyed out and when I try to use it, I get the following warning:
"Cannot generate materials for unknown octane render engine"

I'm using the latest version of the "OctaneRender Prime Free Tier Offer"
2.82a.
Is there anything I may have done wrong?
Or is it just that the addon isn't compatible with this version of Blender/Octane?

With kind regards

**Comment by Yichen-Dou** [comment]
The reason why "Start Megascans Livelink Octane" is grayed out is because the current render engine for Blender is not octane. Please switch on the Octane render engine and try again

**Comment by lemain** [comment]
It worked after I reinstalled the bridge extension and set as you said the render engine to Octane.
Thank you! :)
